### PR TITLE
Pull request for V2

### PR DESCRIPTION
**Pull request by cpldcpu**
This pull request is here to have a place to discuss and document changes leading to v2 Please don't merge yet.

### Todo ###
 - [x]  Synchronize branches

### Firmware ###
 - [x] Document interruptless V-USB
 - [x] Document new protocol
 - [x] New build system to support multiple targets
 - [x] New device configuration reply to support 841
 - [x] Discuss: remove saved osccal? -> leave as option
 - [x] Add support for long jump
 - [ ] Put CRC checking back in.

### Commandline ###
 - [x] New protocol
 - [x] Host side reset vector patching
 - [x] Add support for long jump
 - [x] Add fast mode
 - [x] Set no-ansi as default in windows
 - [x]  Update commandline to support new device reply

### Release ###
 - [ ] Build Windows and Macos binaries of commandline tool.
 - [x] Update documentation

This is a completely new architecture.
  * It does not use any interrupts and does therefore not require INT vector patching. 
  * Current version is 1572 bytes!
  * It's much faster.

### CODE REVIEW

**Comment by cpldcpu** [comment]
*ENABLE_UNSAFE_OPTIMIZATIONS*

Added new global flag to enable unsafe optimizations. This addresses several discussions about potential additional optimization by removing parts of the code that were left in as a fail safe or to support rare special cases. (https://github.com/micronucleus/micronucleus/pull/58)

Currently the only configuration using this is "t85_aggressive", which should not be used if reliable operation is a requirement, anyways. 

Setting this define will disable several safety features in microncleus to save around
40 more bytes

Disabled features:
* Stack pointer and SREG initialization in CRT
* Client side reset vector patching
* USB collision detection. Micronucleus will not work reliability with
hubs if this is disabled.

See t85_aggressive configuration for usage examples.

**Comment by cpldcpu** [comment]
I am cleaning up the repository a bit. I removed ruby and upload, as they are not yet compatible to V2.0. They can be readded later, once they have been updated.

**Comment by cpldcpu** [comment]
@Bluebie: I have pushed V2.0 to master. Please check if you are ok with the readme and so on. I removed some parts that were not updated to V2.0 yet (ruby, upgrade)

@sodabrew: Can you provide an OS X binary of the commandline tool again? There were some updates and I had to remove the last binary to prevent it from being out of sync.

**Comment by cpldcpu** [comment]
@Bluebie: Noticed one more thing: Can you update the tagline of the repository to reflect that not only ATtiny85 is supported? 
"AtTiny85 usb bootloader with a strong emphasis on bootloader compactness. "

**Comment by sodabrew** [comment]
Sure thing, I'll take a look as soon as I can.

**Pull request merged**
