### PR TITLE
integrate build of upgrade submitted by @ArminJo

### PR DESCRIPTION
**Pull request by cpldcpu**
@ArminJo 

I extracted all the necessary changes to include the upgrade build from your submission. Can you check wether this works?

Looked quite straightforward, btw. If you use the toolchain that comes with Atmel studio you don't need the additional binaries and also not the changes to the usb drivers.

### CODE REVIEW

**Comment by ArminJo** [comment]
> I extracted all the necessary changes to include the upgrade build from your submission

Perfect!
So we should document, that it requires Atmel Studio for building the upgrade.

Tests for t85:
The aggressive has 6714 bytes free, my version has 6780 bytes free.
The default has 6522 free, my version has 6650 free.
I guess the Makefile.inc must be changed, or just take my [version](https://github.com/ArminJo/micronucleus-firmware/tree/master/firmware/configuration), it is better documented 😀 I am not able to clone feature_update, so I cannot push changes 😞

**Comment by cpldcpu** [comment]
you should be able to check it out directly via the website?
https://github.com/micronucleus/micronucleus/tree/feature_upgrade

**Comment by cpldcpu** [comment]
I am beginning to wonder a bit about the difference in GCC versions. Maybe mine is too old, but it should be updated by atmel studio.

**Comment by cpldcpu** [comment]
The problem is not the makefile. When I move t85_Aggressive to 1A80, like in your makefile, it does not fit anymore. So it appears that your toolchain generates smaller binaries?

This is the output of mine:



> 
> **********************************************************
> make Configuration t85_aggressive
> **********************************************************
> Building Micronucleus configuration: t85_aggressive
> Size of binary hexfile. Use the "data" size to calculate the bootloader address:
>    text    data     bss     dec     hex filename
>       0    1410       0    1410     582 main.hex
>    text    data     bss     dec     hex filename
>       0    2122       0    2122     84a upgrade.hex
> 
> **********************************************************
> make Configuration t85_default
> **********************************************************
> Building Micronucleus configuration: t85_default
> Size of binary hexfile. Use the "data" size to calculate the bootloader address:
>    text    data     bss     dec     hex filename
>       0    1564       0    1564     61c main.hex
>    text    data     bss     dec     hex filename
>       0    2276       0    2276     8e4 upgrade.hex

**Comment by ArminJo** [comment]
> you should be able to check it out directly via the website?

I learned that no one is interested in the size of the micronucleus, all are interested in the remaining size for their code.

> I am beginning to wonder a bit about the difference in GCC versions. Maybe mine is too old, but it should be updated by atmel studio.

With the version 2_5 sources I also get your figures (even 2 bytes more)

> The problem is not the makefile. When I move t85_Aggressive to 1A80, like in your makefile, it does not fit anymore. So it appears that your toolchain generates smaller binaries?

For aggressive, I use the modified usbdrvasm16.inc wich is modified with the same modications as tested for the usbdrvasm165.inc used for t85_default. This may explain part of the smaller size. I checked my version in.

But for the rest I found only a change in crt1.S where I removed 	out		0x3f,r1 (-2 bytes)

The rest I cannot really compare, since I removed all the unused legacy code and comments, so the diffs are not readable any more.

**Comment by cpldcpu** [comment]
@ArminJo everything should be in now. I also recalculated all bootloader start addresses. In average one page was saved.

**Comment by cpldcpu** [comment]
Ok, merging this branch so I can delete it.

@ArminJo, i have not been able to test many of the hexfile after changing bootloader start addresses. I guess everything is still ok, as there was no issue during compilation.

**Pull request merged**
