### PR TITLE
aded python script to create c include file from boot.hex for bootloader upgrade

### PR DESCRIPTION
**Pull request by Ho-Ro**

### CODE REVIEW

**Comment by Ho-Ro** [comment]
I've hacked a python script as an alternative to the ruby (there is more than one way to do it), both scripts create the same output.

**Comment by Ho-Ro** [comment]
was closed by mistake...

**Comment by Bluebie** [comment]
whats the point of using python instead of ruby

**Comment by Ho-Ro** [comment]
Some people here don't have a ruby environment - mainly on their windows systems. Python is easier to install, also as a portable solution. 
This was also the reason for me to provide pre-built upgrade*.hex files some days ago. There are a lot of china clones sold with old bootloader version 1.6. This bootloader seems less stable than current 2.3. On my system I constantly got "Eep! Connection lost" errors with 1.6, these were gone with 2.3.

**Comment by Ho-Ro** [comment]
BTW - It would be the cleanest solution to use the AVR toolchain to create a boot.o and link it together with upgrade.o. I saw that some steps are already taken - I was able to create the *.o files but the final linking didn't work "avr-ld -o upgrade.bin upgrade.o boot.o produced a bin and finally an intel hex with the bootloader content stating at address 0000 and the parts of upgrade.c at higher addresses :(

**Comment by cpldcpu** [comment]
@Ho-Ro 

Indeed, that was the solution I was striving for. This would instantly remove the need for any script and could fully automate the build from the makefile. There was still some confusion about the linking and generating symbols for the C-compiler, so update.c can access the hex. That's why development stalled at some point.

**Comment by Ho-Ro** [comment]
Finally, I found the solution how to build the upgrade.hex only with the AVR toolchain and without extra ruby, python,... scripts! I double checked the code, crossed my fingers and upgraded one of my digispark clones - it came to life again - phew! (if it hadn't survived, I'd have to pick out my STK500 and get it up and running.) 
Everything takes place in the firmware directory and produces by default a "boot.hex" and an "upgrade.hex" with attiny85_default configuration.

**Comment by cpldcpu** [comment]
Thank you, that looks great. You solved a long standing open issue. I still have to test it though.

Before I break anything: It should be possible to remove the python files now?

utils.h is from the original upgrade.h, I suppose?

**Comment by Ho-Ro** [comment]
The complete upgrade mechanism lives now in directory "firmware" - complete directory "upgrade" is now no longer needed - I added a README.upgrade. 
I just made a small change to the Makefile, now it builds "main.hex" and then "upgrade.hex" using "main.hex" from 1. step. (the old version used releases/$CONFIG.hex). Also added a script to build all main.hex and upgrade.hex for all available configurations.
Please test! I was able to check it on my debian stable using a digispark china clone board.

**Comment by ArminJo** [comment]
It worked like a charm for me on W10 and I would like it to see in the master branch.

**Pull request merged**
