### PR TITLE
[Non-Tested] Initial beta support for atmega328p

### PR DESCRIPTION
**Pull request by mihaigalos**
It will take at least a month before the HW is ready, but in the meantime, if anybody can test or improve, I would love to see official support for atmega328p.

### CODE REVIEW

**Comment by mihaigalos** [comment]
It will take at least a month before the HW is ready, but in the meantime, if anybody can test or improve, I would love to see official support for atmega328p.

**Comment by AHorneffer** [comment]
Hi. I don't have everything together to really give it a test, but I do have some questions, comments:

As far as I can tell, the fuse-settings `0xe1` for the clocks are invalid. Setting `CKSEL[0:3]` to 0001 is listed as "reserved" in the datasheet that I have here. Shouldn't the low-fuse be `0xff` if one uses an external crystal? Also, wouldn't it make sense to set `OSCCAL_HAVE_XTAL` in the configuration in that case?  
The `0x52` uses the internal clock but divides the clock by 8? So it'll running at about 1MHz. (And, well, it doesn't fit the `F_CPU` value of 16MHz.)

Do I see it correctly that this uses pins `PC0` for `D-` and `PC1` for `D+`, i.e. pins 23 and 24 on the atmega328p-pu? 

The "BOOTLOADER_ADDRESS" is this the page-number, the word-number, or the byte number? Also, should the bootloader start at the address given by the boot size fuses?

**Comment by mihaigalos** [comment]
I have edited the comments and left it out in the options..
Ex: FF Hi: D8 Lo: 52. 

For the calculation of BOOTLOADER_ADDRESS you can have a look at the following snipped taken from t85_default/Makefile.inc

# hexadecimal address for bootloader section to begin. To calculate the best value:
# - make clean; make main.hex; ### output will list data: 2124 (or something like that)
# - for the size of your device (8kb = 1024 * 8 = 8192) subtract above value 2124... = 6068
# - How many pages in is that? 6068 / 64 (tiny85 page size in bytes) = 94.8125
# - round that down to 94 - our new bootloader address is 94 * 64 = 6016, in hex = 1780
BOOTLOADER_ADDRESS = 1980

Of course I will address the shortcomings in the following patchsets.

**Comment by mihaigalos** [comment]
Update : successfully tested on a atmega328p with no further modification!

I have only flashed the bootloader hex file (no fuse altering).
The board already had the following fuses : 
`LO=0xFF HI=0xD8 EXT=0xEF (16Mhz external oscillator, bootrst enabled, bootsize = 2048)`

Next, I've used the same command used by the Digispark to flash a blink binary :
`C:\Users\Mihai\AppData\Local\Arduino15\packages\digistump\tools\micronucleus\2.0a4/launcher -cdigispark --timeout 60 -Uflash:w:C:\Users\Mihai\AppData\Local\Temp\arduino_build_349316/blink.ino.hex:i`

Output:
`connecting: 16% complete
connecting: 22% complete
connecting: 28% complete
connecting: 33% complete
> Device has firmware version 2.3
> Device signature: 0x1e950f
> Available space for user applications: 14330 bytes
> Suggested sleep time between sending pages: 7ms
> Whole page count: 112  page size: 128
> Erase function sleep duration: 784ms
parsing: 50% complete
> Erasing the memory ...
erasing: 55% complete
erasing: 60% complete
erasing: 65% complete
> Starting to upload ...
writing: 70% complete
writing: 75% complete
writing: 80% complete
> Starting the user app ...
running: 100% complete
>> Micronucleus done. Thank you!`

**Comment by AHorneffer** [comment]
Did you check if the issues I listed in #107 work?

**Comment by mihaigalos** [comment]
I can confirm your observations. Let's move the discussion to that thread.

**Comment by mihaigalos** [comment]
Can be found [here](https://github.com/AHorneffer/micronucleus/tree/atmega328p). Will probably be integrated into master.

**Pull request closed without merging**
