### PR TITLE
Script for building executables and pushing then back to repo

### PR DESCRIPTION
**Pull request by ArminJo**
This script only runs if the micronucleus-cli files are changed (every 2 years or so 😀 ).
It pushes the executables back to the repo, so that they are easy available and included in every release.

In this PR the executables are included, but the only change is  the addition of [this workflow definition file](https://github.com/ArminJo/micronucleus/blob/master/.github/workflows/BuildBinaries.yml).

The 32 bit Linux and the ARM versions are still included 😀

### CODE REVIEW

**Comment by cpldcpu** [comment]
Nice, you figured out the built scripts! It's still a bit confusing to me. Merging right away.

I am wondering: Wouldn't it make somehow sense to generated a released archive that only containts binaries and hex files? Usually people don't need to source, so distributing both seperatately makes a lot of sense.

**Comment by cpldcpu** [comment]
@ArminJo It seems to me that there is a bit of mix-up bitween this and your repository?

grafik

**Comment by cpldcpu** [comment]
Ah ok, these were all the commits that were merged when I merged your branch. I wonder why only Darwin and Windows were updated in the new branch?

To be honest, seeing this now, I wonder whether there is somehow a away to prevent all of the scripted activity to show up in the commit history? This is a bit confusing, because it does not allows distinguishing actual code change. Basically it will add a lot of activity when something is changed in the tool.

**Comment by ArminJo** [comment]
I tried more than 10 hours do avoid this additional commits, but amending does not work, since the building jobs are parallel.
And additionally there is no way to get deterministic builds for windows and MacOs, only Linux support it.
So if you change a comment or even the build yml, at least the Windows and MacOs binaries are different (4 bytes at the beginning) and lead to a commit.
Keep in mind, that I have included the __DATE__ in the sources, which I find very very useful, thus after one day all sources are different and commited anyway. This leads to only **2 commits**, one "executable for" and one "merge branch". I do not really understand the reason for one "merge branch" instead of having more "executable commits", since I am no git guru.

I can change this to a serial build, this is a bit more effort, but may worth it. Your opinion?

**Comment by ArminJo** [comment]
> I am wondering: Wouldn't it make somehow sense to generate a release archive that only contains binaries and hex files? Usually people don't need the source, so distributing both seperatately makes a lot of sense.

Most people are using micronucleus by means of an Arduino core, where it is included. And for the others we have them incuded in the builds directory.
But I find it a good idea to put a link to the executables in the Readme, maybe like the well nown "Download" buttons.
IMHO a separate archive is too much.

**Comment by cpldcpu** [comment]
We should probabyl add a linke to this:

https://github.com/micronucleus/micronucleus/releases/tag/master-LATEST

**Comment by ArminJo** [comment]
Just for info: I am now finished with the integration and deleted my local part of commandline now 😀

**Comment by quinot** [comment]
Hmmm I was about to merge my own version of the crossbuild for ARM but I see you have these in already...
I'd strongly suggest avoiding pushing binaries back to the repo. The proper location for binaries is in release artefacts. The source git repo is really not meant for storage of build products.

**Comment by ArminJo** [comment]
You maybe right, but this is a contradiction to the storage of the *.hex files in releases and updates!

**Comment by cpldcpu** [comment]
>I'd strongly suggest avoiding pushing binaries back to the repo. The proper location for binaries is in release artefacts. The source git repo is really not meant for storage of build products.

Thanks for confirming this from another perspective :). I agree 100%

>You maybe right, but this is a contradiction to the storage of the *.hex files in releases and updates!

It actually is. But the release system was implemented in github way after micronucleus was set up in that way. I would prefer to put all the hexfiles into the binary releases too. Just need to find a way to automate this. I will test the "make all" extension. If that works we can at least build releases without OS specific scripts. That would be a big step.

**Comment by cpldcpu** [comment]
For some reason we get build errors now?! Nothing was changed in the command line tool...

grafik

**Comment by ArminJo** [comment]
I would prefere to have a separate repository for binaries and hex files as you suggested before 😀 
Pushing files can be done by using git in the workflow, which buils it.

**Pull request merged**
