### PR TITLE
Add a warning in comments for AUTO_EXIT_MS low values

### PR DESCRIPTION
**Pull request by jej**

### CODE REVIEW

**Comment by cpldcpu** [comment]
done

**Comment by jej** [comment]
Hi Tim,

In fact, I cannot test this hypothesis ("values smaller than 1000 may break the device") because I don't want to break another device!... I don't have an attiny with reset enabled. I cannot be 100% sure that the reason of the problem encountered was here, and I had no opportunity to try again. If you can test on your side, maybe that's better.
What do you think about that?
J.

**Comment by cpldcpu** [comment]
Hi J.,

I solved this by throwing an error when the timeout is set below 1s:
https://github.com/micronucleus/micronucleus/blob/master/firmware/main.c#L42

**Comment by jej** [comment]
Yes, but are you really sure that a timeout<1s really breaks the device? I experienced this problem when I was playing with micronucleus compilation on my digispark, at my first steps with this firmware. But I confess I cannot be sure of this fact.
Did you try for example to set a timeout of 250ms? I don't want to be locked again so I prefer not to play again :)

**Comment by jej** [comment]
PS: you can see this post as reminder: https://github.com/micronucleus/micronucleus/issues/61
The death value is theoretically 792 (but don't want to test again and lock another digispark...)

**Comment by cpldcpu** [comment]
I have a USB3.0 hub that takes around 2s to enumerate. Pretty sure that micronucleus would fail at 1s

**Comment by cpldcpu** [comment]
Setting the timout low is also not the way if reducing delay caused by the bootloader. I you need to define a proper entry condition and not start the bootloader at all, when you dont need it.

**Comment by jej** [comment]
Al right, thanks for the confirmation!
J.

**Pull request closed without merging**
